version: "3.8"  # или нужная вам версия

services:
  pg:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      env_file: ".env"

  webserver:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www/:/var/www/certbot/:ro
    depends_on:
      - bot
    networks:
      - backend

  certbot:
    image: certbot/certbot:alpine
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    networks:
      - backend

  bot:
    build:
      context: .
      dockerfile: ./docker/bot.Dockerfile
    container_name: bot
    env_file: ".env"
    depends_on:
      - pg
    networks:
      - backend

networks:
  backend:
    driver: bridge
